// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxDFjjmNwUgGdAV4vuNvJduh0jO_bsA0g',
    appId: '1:386813086476:web:5e35ba51e1005cda891729',
    messagingSenderId: '386813086476',
    projectId: 'dojo-c0e21',
    authDomain: 'dojo-c0e21.firebaseapp.com',
    storageBucket: 'dojo-c0e21.appspot.com',
    measurementId: 'G-NWEMFDZ5J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTAuaDZ3EJAq1I50WAGeUlBVBFpgQdRtc',
    appId: '1:386813086476:android:8f6b89b150a18085891729',
    messagingSenderId: '386813086476',
    projectId: 'dojo-c0e21',
    storageBucket: 'dojo-c0e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzw8ZTy4SqRciZ-Xox6a71dls59jYTw08',
    appId: '1:386813086476:ios:95bcc9ae48bf9db4891729',
    messagingSenderId: '386813086476',
    projectId: 'dojo-c0e21',
    storageBucket: 'dojo-c0e21.appspot.com',
    iosClientId: '386813086476-f0qptsahp3dsmuim0t3hbeaqeqhcjmh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dojo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzw8ZTy4SqRciZ-Xox6a71dls59jYTw08',
    appId: '1:386813086476:ios:95bcc9ae48bf9db4891729',
    messagingSenderId: '386813086476',
    projectId: 'dojo-c0e21',
    storageBucket: 'dojo-c0e21.appspot.com',
    iosClientId: '386813086476-f0qptsahp3dsmuim0t3hbeaqeqhcjmh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dojo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxDFjjmNwUgGdAV4vuNvJduh0jO_bsA0g',
    appId: '1:386813086476:web:2f5407cd7c559df5891729',
    messagingSenderId: '386813086476',
    projectId: 'dojo-c0e21',
    authDomain: 'dojo-c0e21.firebaseapp.com',
    storageBucket: 'dojo-c0e21.appspot.com',
    measurementId: 'G-346HD8B1YS',
  );
}
